### ISSUE TITLE
Cannot enable annotation based scraping for endpoints (Kubernetes services)

### ISSUE THREAD

**Issue by lk-1984** [Azure/prometheus-collector#762]
I am modifying Configmap "ama-metrics-prometheus-config". My scrape job is:

```
      - job_name: kubernetes-service-endpoints
        scrape_interval: 30s
        label_limit: 63
        label_name_length_limit: 511
        label_value_length_limit: 1023
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)(?::\d+);(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name
```

But the prometheus-collector cannot load this configuration.

```
 prometheus-collector ******************Done Merging Default and Custom Prometheus Config*******************                                  │
│ prometheus-collector prom-config-validator::Config file provided - /opt/promMergedConfig.yml                                                 │
│ prometheus-collector prom-config-validator::Successfully generated otel config                                                               │
│ prometheus-collector prom-config-validator::Loading configuration...                                                                         │
│ prometheus-collector prom-config-validator::Cannot load configuration: cannot unmarshal the configuration: 1 error(s) decoding:              │
│ prometheus-collector                                                                                                                         │
│ prometheus-collector * error decoding 'receivers': error reading configuration for "prometheus": prometheus receiver failed to unmarshal yam │
│ prometheus-collector prom-config-validator::Prometheus custom config validation failed. The custom config will not be used                   ││ prometheus-collector prom-config-validator::Running validator on just default scrape configs                                                 ││ prometheus-collector prom-config-validator::Config file provided - /opt/defaultsMergedConfig.yml                                             ││ prometheus-collector prom-config-validator::Successfully generated otel config                                                               ││ prometheus-collector prom-config-validator::Loading configuration...                                                                         ││ prometheus-collector prom-config-validator::Successfully loaded and validated prometheus config                                              ││ prometheus-collector prom-config-validator::Use default prometheus config: true  
```

We do not use annotations on pods in our product, we use them on services.
