### ISSUE TITLE
Unable to add external labels to ama-metrics pods

### ISSUE THREAD

**Issue by prombeginner** [Azure/prometheus-collector#889]
Hi

I've updated both "ama-metrics-prometheus-config" and "ama-metrics-prometheus-config-node" configmaps with the following settings:
```
data:
  prometheus-config: |
    global:
      external_labels:
        my_fqdn: sample_fqdn
```

However only the pods for "ama-metrics-node-*" receive the external_labels configuration.
Why are the other pods ignoring the configmap?

thank you for your time.

**Comment by vishiy** [comment]
@prombeginner - Thank you for reporting this. We will look into it today and post back..

**Comment by vishiy** [comment]
@prombeginner - This is an issue. Can you please work this around, as we fix this?

If you are using config map , just use metric relabeling to add the label (you would need to add this for each job in it relabel config)

  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:8000']
    relabel_configs:
      # address label below will always exist for any target. so just replace that with your my-label and its value (my-label-value)
      - source_labels: [__address__]
        target_label: my-label
        replacement: "my-label-value"
        
     Will keep this open until we fix this issue. Please let us know if you need more help.

**Comment by prombeginner** [comment]
Hi Vishiy, could you help me out a little more?

I've tried applying the following configuration to the configmap "ama-metrics-prometheus-config"
```
apiVersion: v1
data:
  prometheus-config: |
    scrape_configs:
    - job_name: kube-state-metrics
      static_configs:
      - targets: ['localhost:8000']
      relabel_configs: 
      - source_labels: [address]
        target_label: sentia_fqdn
        replacement: "my-label-value"
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
```
But afterwards I receive the following error:
```
prometheus-collector prom-config-validator::Cannot load configuration: cannot unmarshal the configuration: 1 error(s) decoding: "* error decoding 'receivers': error reading configuration for "prometheus": prometheus receiver failed to unmarshal"
prometheus-collector prom-config-validator::Prometheus custom config validation failed. The custom config will not be used 
prometheus-collector prom-config-validator::Running validator on just default scrape configs
```

I tried disabling the default kubestate scrape settings in ama-metrics-settings-configmap and adding my configuration with the defaults but now i'm no longer receiving metrics.
